lib/auth_pow_web/router.ex
defmodule AuthPowWeb.Router do
  use AuthPowWeb, :router
  use Pow.Phoenix.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {AuthPowWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :protected do
    plug Pow.Plug.RequireAuthenticated,
      error_handler: Pow.Phoenix.PlugErrorHandler
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/" do
    pipe_through :browser

    pow_routes()
  end

  scope "/", AuthPowWeb do
    pipe_through :browser

    get "/", PageController, :index
    # get "/articles/:id", ArticleController, :new

    resources "/articles", ArticleController do
      resources "/comments", CommentController
      # , only: [:index, :show]
    end
    # get "/articles/:id", ArticleController, :show

  end


  scope "/", AuthPowWeb do

    pipe_through [:browser, :protected]
    # resources "/articles", ArticleController, only: [:index, :create] do
      # resources "/comments", CommentController, only: [:index, :create]
    # end
    # do
    #   get "/comments/:id", CommentController , :
    # end


  end


  # Other scopes may use custom stacks.
  # scope "/api", AuthPowWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: AuthPowWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/auth_pow/chats/comment.ex
defmodule AuthPow.Chats.Comment do
  use Ecto.Schema
  import Ecto.Changeset

  schema "comments" do
    field :message, :string

    belongs_to :article, AuthPow.Articles.Article
    belongs_to :user, AuthPow.Users.User

    timestamps()
  end

  @doc false
  def changeset(comment, attrs) do
    comment
    |> cast(attrs, [:message, :user_id, :article_id])
    |> validate_required([:message,:user_id, :article_id ])
  end
end

lib/auth_pow_web/controllers/comment_controller.ex
defmodule AuthPowWeb.CommentController do
  use AuthPowWeb, :controller

  alias AuthPow.Articles.Article
  alias AuthPow.Chats
  alias AuthPow.Chats.Comment
  alias AuthPow.Repo

  def index(conn, params) do
    %{"article_id" => id} = params
    comments = Chats.list_comments
    render(conn, "index.html", comments: comments, article_id: String.to_integer(id))
  end

  def new(conn, params) do
    IO.inspect("New+++++++++++++++++")
    # IO.inspect Pow.Plug.current_user(conn).id
     %{"article_id" => id} = params
      article_id = String.to_integer(id)
     changeset = Chats.change_comment(%Comment{})
     comment = article_id
    # IO.inspect(changeset)
    render(conn, "new.html", comment: comment, changeset: changeset,article_id: comment)
  end

  def create(conn, %{"comment" => comment_params,"article_id" => id }) do
    IO.inspect("++++++++++COmment Create+++++++++++")
    #
    article_id = String.to_integer(id)
    article = Repo.get(Article,article_id)
    # userid = Pow.Plug.current_user(conn)
    # IO.inspect()
    comment = struct(Comment)
    IO.inspect(comment)
    IO.inspect(article_id)
    IO.inspect article.user_id
    IO.inspect(comment_params)
    comment_params = Map.put(comment_params,"user_id",article.user_id)
    comment_params = Map.put(comment_params,"article_id",article.id)

    # comment_changeset = Ecto.build_assoc(article, :comment, %{message: comment["message"], user_id: article.user_id["user_id"], article_id: id["article_id"]})
    IO.inspect(comment_params)
    # IO.inspect(conn)

    IO.inspect(%Comment{})
    # repo_comment = Repo.get(Article, article_id)
    IO.inspect("repo_comment")
    # IO.inspect(repo_comment)
    # comment = Map.put(comment,"article_id",article_id)
    # comment_params = Map.put(comment_params,"article_id",id)
    IO.inspect(comment_params)
    # IO.inspect Chats.create_comment(comment_params)
    # conn
    # |> put_flash(:info, "Comment created successfully.")
    # |> redirect(to: Routes. article_comment_path(conn, :show, comment.article_id, comment.id))
    # IO.inspect comment_params.article_id
    # , comment_params.article_id, comment_params.id
    case Chats.create_comment(comment_params) do
      {:ok, body} ->
        IO.inspect(body.id)
        conn
        |> put_flash(:info, "Comment created successfully.")
        |> redirect(to: Routes. article_comment_path(conn, :show, body.article_id, body.id))

    #   {:error, %Ecto.Changeset{} = changeset} ->
    #     IO.inspect("Errrorrr")
    #     # IO.inspect(article_id)
    #     # IO.inspect("comment")
    #     # IO.inspect(comment)
    #     # render(conn, "new.html", comment: comment)
    end
  end
  # %{"id" => id}, %{"message" => message, "article_id" => article_id}
  def show(conn, %{"id" => id} ) do
    IO.inspect("+++++++++++Show+++++++++++++")
    # IO.inspect(article_id)
    # IO.inspect(message)

    comment = Chats.get_comment!(id)
    IO.inspect(comment.article_id)
    render(conn, "show.html", comment: comment)
  end

  def edit(conn, %{"id" => id}) do
    comment = Chats.get_comment!(id)
    changeset = Chats.change_comment(comment)
    render(conn, "edit.html", comment: comment, changeset: changeset)
  end

  def update(conn, %{"id" => id, "comment" => comment_params}) do
    comment = Chats.get_comment!(id)

    case Chats.update_comment(comment, comment_params) do
      {:ok, comment} ->
        conn
        |> put_flash(:info, "Comment updated successfully.")
        |> redirect(to: Routes. article_comment_path(conn, :show, comment))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", comment: comment, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    comment = Chats.get_comment!(id)
    {:ok, _comment} = Chats.delete_comment(comment)

    conn
    |> put_flash(:info, "Comment deleted successfully.")
    |> redirect(to: Routes.article_comment_path(conn, :index))
  end
end

lib/auth_pow_web/views/comment_view.ex
defmodule AuthPowWeb.CommentView do
  use AuthPowWeb, :view
end

lib/auth_pow_web/templates/comment/edit.html.heex
<h1>Edit Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.comment_path(@conn, :update, @comment)) %>

<span><%= link "Back", to: Routes.comment_path(@conn, :index) %></span>

lib/auth_pow_web/templates/comment/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :message %>
  <%= text_input f, :message %>
  <%= error_tag f, :message %>
  
  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/auth_pow_web/templates/comment/index.html.heex
<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Message</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for comment <- @comments do %>
    <tr>
      <td><%= comment.message %></td>

      <td>
        <span><%= comment.article_id%></span>
        <span><%= link "Show", to: Routes.article_comment_path(@conn, :show, comment.article_id, comment.id) %></span>
        <span><%= link "Edit", to: Routes.article_comment_path(@conn, :edit, comment.article_id, comment.id) %></span>
        <span><%= link "Delete", to: Routes.article_comment_path(@conn, :delete, comment.article_id, comment.id), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>
<div>
       <span><%= link "New comment", to: Routes.article_comment_path(@conn, :new, @article_id) %></span>
</div>

lib/auth_pow_web/templates/comment/new.html.heex
<h1>New Comment</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.article_comment_path(@conn, :create, @comment)) %>

<span><%= link "Back", to: Routes.article_comment_path(@conn, :index, @comment) %></span>

lib/auth_pow_web/templates/comment/show.html.heex
<h1>Show Comment</h1>

<ul>

  <li>
    <strong>Message:</strong>
    <%= @comment.message %>
  </li>

</ul>

<span><%= link "Edit", to: Routes.article_comment_path(@conn, :edit, @comment.article_id, @comment.id) %></span> |
<span><%= link "Back", to: Routes.article_comment_path(@conn, :index, @comment.article_id) %></span>